=== BuiTanDuoc/semestre6/SI2/Práticas/31401/catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tanenaCatalog:catalog (( category+ )) >
<!ATTLIST tanenaCatalog:catalog
	xmlns:tanenaCatalog CDATA #FIXED "http://TantrasEnamour/Catalog"
>
<!ATTLIST category
	cat_name	CDATA	#REQUIRED
>
<!ELEMENT category ((course+))>
<!ELEMENT course ((ingredient,confection))>
<!ATTLIST course
	course_id		CDATA	#REQUIRED
	course_name		CDATA	#REQUIRED
	course_price	CDATA	#REQUIRED
>
<!ELEMENT ingredient ((ingredientRecord+))>
<!ELEMENT ingredientRecord EMPTY>
<!ELEMENT confection (#PCDATA)>
<!ATTLIST ingredientRecord 
	id			CDATA	#REQUIRED
	nome	CDATA	#REQUIRED
	qtd		CDATA	#REQUIRED
	unidade	CDATA	#REQUIRED
>

=== BuiTanDuoc/semestre6/SI2/Práticas/31401/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "C:\WorkingArea\ISEL\semestre6\SI2\PrÃ¡ticas\31401\catalog.dtd">
<catalog>
	<category cat_name="Nome da Categoria">
		<course course_id="0" course_name="Nome do Prato" course_price="0.0">
			<ingredient>
				<ingredientRecord id="ID" nome="NOME" qtd="Quantidade" unidade="Kg"/>
				<ingredientRecord id="ID" nome="NOME" qtd="Quantidade" unidade="Kg"/>
				<ingredientRecord id="ID" nome="NOME" qtd="Quantidade" unidade="Kg"/>
				<ingredientRecord id="ID" nome="NOME" qtd="Quantidade" unidade="Kg"/>
				<ingredientRecord id="ID" nome="NOME" qtd="Quantidade" unidade="Kg"/>
				<ingredientRecord id="ID" nome="NOME" qtd="Quantidade" unidade="Kg"/>
			</ingredient>
			<confection>
        Bla Bla Bla
      </confection>
		</course>
	</category>
</catalog>
