=== BuiTanDuoc/semestre6/SI2/Práticas/31401/stockTransfer.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tanenaStockTransfer:stockTransfer ((transaction+))>
<!ELEMENT transaction (restaurantFrom,restaurantTo)>
<!ELEMENT restaurantFrom ((ingredient+))>
<!ELEMENT ingredient	EMPTY>
<!ELEMENT restaurantTo EMPTY>

<!ATTLIST tanenaStockTransfer:stockTransfer
	xmlns:tanenaStockTransfer CDATA #FIXED "http://TantrasEnamour/stockTransfer"
>
<!ATTLIST 	transaction
	id		CDATA		#REQUIRED
>
<!ATTLIST	restaurantFrom
	id		CDATA		#REQUIRED
	name	CDATA		#REQUIRED
>
<!ATTLIST	ingredient
	id			CDATA	#REQUIRED
	name		CDATA	#REQUIRED
	quantity	CDATA	#REQUIRED
	unit		CDATA	#REQUIRED
>
<!ATTLIST	restaurantTo
	id			CDATA	#REQUIRED
	name		CDATA	#REQUIRED
>

=== BuiTanDuoc/semestre6/trunk/SI2/Práticas/TantrasEnamour/XML/stockTransfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE tanenaStockTransfer:stockTransfer SYSTEM "stockTransfer.dtd">-->
<?xml-stylesheet type="text/xsl" href="stockTransfer.xslt"?>
<ns:stockTransfer xmlns:ns="http://TantrasEnamour/stockTransfer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TantrasEnamour/stockTransfer stockTransfer.xsd">
	<ns:transaction id="1291">
		<ns:restaurantFrom id="1" name="Restaurant Name">
			<ns:ingredient id="1" name="Ingredient Name" quantity="20" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="2" name="Ingredient Name" quantity="1.2" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="3" name="Ingredient Name" quantity="3.4" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="4" name="Ingredient Name" quantity="6" unit="kg" vality="2011-12-31"/>
		</ns:restaurantFrom>
		<ns:restaurantTo id="2" name="Restaurant Name"/>
	</ns:transaction>
		<ns:transaction id="1292">
		<ns:restaurantFrom id="1" name="Restaurant Name">
			<ns:ingredient id="4" name="Ingredient Name" quantity="1" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="5" name="Ingredient Name" quantity="1.2" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="6" name="Ingredient Name" quantity="3.4" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="7" name="Ingredient Name" quantity="6" unit="kg" vality="2011-12-31"/>
		</ns:restaurantFrom>
		<ns:restaurantTo id="2" name="Restaurant Name"/>
	</ns:transaction>
		<ns:transaction id="1293">
		<ns:restaurantFrom id="1" name="Restaurant Name">
			<ns:ingredient id="1" name="Ingredient Name" quantity="1" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="1" name="Ingredient Name" quantity="1.2" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="1" name="Ingredient Name" quantity="3.4" unit="kg" vality="2011-12-31"/>
			<ns:ingredient id="1" name="Ingredient Name" quantity="6" unit="kg" vality="2011-12-31"/>
		</ns:restaurantFrom>
		<ns:restaurantTo id="1292" name="Restaurant Name"/>
	</ns:transaction>
</ns:stockTransfer>

=== BuiTanDuoc/semestre6/SI2/Práticas/31401/stockTransfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stockTransfer SYSTEM "C:\WorkingArea\ISEL\semestre6\SI2\Práticas\31401\stockTransfer.dtd">
<stockTransfer>
	<transaction id="Id da transacção">
		<restaurantFrom id="Restaurant Id" name="Restaurant Name">
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
		</restaurantFrom>
		<restaurantTo id="Restaurant Id" name="Restaurant Name"/>
	</transaction>
</stockTransfer>

=== BuiTanDuoc/semestre6/trunk/SI2/Práticas/31401/stockTransfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tanenaStockTransfer:stockTransfer SYSTEM "stockTransfer.dtd">
<tanenaStockTransfer:stockTransfer xmlns:tanenaStockTransfer="http://TantrasEnamour/stockTransfer">
	<transaction id="Id da transacção">
		<restaurantFrom id="Restaurant Id" name="Restaurant Name">
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
			<ingredient id="Ingredient ID" name="Ingredient Name" quantity="Quantidade" unit="Unidade"/>
		</restaurantFrom>
		<restaurantTo id="Restaurant Id" name="Restaurant Name"/>
	</transaction>
</tanenaStockTransfer:stockTransfer>
