=== BuiTanDuoc/semestre6/SI2/Práticas/31401/Untitled1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Temperatura">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Local" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="LocalValorUnico">
			<xs:selector xpath="Local"/>
			<xs:field xpath="@nome"/>
		</xs:unique>
	</xs:element>
	<xs:element name="Temp">
		<xs:complexType>
			<xs:attribute name="Min" type="xs:byte" use="optional"/>
			<xs:attribute name="Max" type="xs:byte"/>
			<xs:attribute name="Dia" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Local">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Temp" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="nome" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:unique name="LocalValorUnico2">
			<xs:selector xpath="Temp"/>
			<xs:field xpath="@Dia"/>
		</xs:unique>
	</xs:element>
	<xs:simpleType name="minimumTemperature">
		<xs:restriction xmlns:xs="http://www.w3.org/2001/XMLSchema" base="xs:int">
			<xs:minInclusive value="-60"/>
		</xs:restriction>
	</xs:simpleType>

=== BuiTanDuoc/semestre6/trunk/SI2/Práticas/31401/Untitled2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Temperatura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Untitled1.xsd">
<Local nome="Lisboa">
<Temp Dia="2011-01-01" Max="15" Min="08"/>
<Temp Dia="2011-01-04" Max="10"/>
</Local>
<Local nome="Porto">
<Temp Dia="2011-01-01" Min="08"/>
<Temp Dia="2011-01-02" Max="17" Min="12"/>
</Local>

<Local nome="Coimbra"/>


</Temperatura>
