=== BuiTanDuoc/semestre6/SI2/Práticas/TantrasEnamour/XML/competences.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
<xs:element name="competence">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="compCount" type="xs:integer" use="required"/>
		</xs:complexType>
</xs:element>
	
<xs:element name="restaurant">	
	<xs:complexType >
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element ref="competence" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
</xs:element>
	
<xs:element name="competences">
	<xs:complexType>
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element ref="restaurant"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
	
</xs:schema>

=== BuiTanDuoc/semestre6/trunk/SI2/Práticas/TantrasEnamour/XML/Alinea6.xml
<?xml version="1.0" encoding="UTF-8"?>
<competences xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="competences.xsd">
  <restaurant id="2" name="La Tartine">
    <competence name="Chef                " compCount="3" />
  </restaurant>
  <restaurant id="1" name="TantrasEnamour">
    <competence name="Chef                " compCount="1" />
    <competence name="Sous-Chef           " compCount="1" />
    <competence name="Commis              " compCount="1" />
  </restaurant>
  <restaurant id="3" name="LA COCAGNE">
    <competence name="Chef                " compCount="1" />
    <competence name="Sous-Chef           " compCount="1" />
    <competence name="Commis              " compCount="1" />
  </restaurant>
  <restaurant id="4" name="Tête à Tête">
    <competence name="Chef                " compCount="1" />
    <competence name="Sous-Chef           " compCount="1" />
    <competence name="Commis              " compCount="1" />
  </restaurant>
</competences>
