=== BuiTanDuoc/semestre6/trunk/SI2/Práticas/31401/catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tanenaCatalog="http://TantrasEnamour/Catalog" targetNamespace="http://TantrasEnamour/Catalog">
	<xs:element name="catalog" nillable="true">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="category" nillable="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="course" nillable="true">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ingredient" nillable="true">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ingredientRecord" nillable="true"  maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:integer" use="required"/>
															<xs:attribute name="nome" type="xs:string" use="required"/>
															<xs:attribute name="qtd" type="xs:decimal" use="required"/>
															<xs:attribute name="unidade" type="xs:string" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="confection" type="xs:string" nillable="false" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
									<xs:attribute name="course_id" type="xs:int" use="required"/>
									<xs:attribute name="course_name" type="xs:string" use="required"/>
									<xs:attribute name="course_price" type="xs:decimal" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="category_name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BuiTanDuoc/semestre6/trunk/SI2/Práticas/TantrasEnamour/XML/catalog.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tanenaCatalog:catalog xmlns:tanenaCatalog="http://TantrasEnamour/Catalog"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TantrasEnamour/Catalog catalog.xsd">
	<tanenaCatalog:category category_name="Nome da Categoria">
		<tanenaCatalog:course course_id="0" course_name="Nome do Prato" course_price="0.0">
			<tanenaCatalog:ingredient>
					<tanenaCatalog:ingredientRecord id="0" name="NOME" quantity="1" unit="kg"/>
					<tanenaCatalog:ingredientRecord id="1" name="NOME" quantity="1" unit="kg"/>
					<tanenaCatalog:ingredientRecord id="2" name="NOME" quantity="1.3" unit="kg"/>
					<tanenaCatalog:ingredientRecord id="3" name="NOME" quantity="2" unit="kg"/>
					<tanenaCatalog:ingredientRecord id="4" name="NOME" quantity="6" unit="kg"/>
					<tanenaCatalog:ingredientRecord id="5" name="NOME" quantity="10" unit="kg"/>
			</tanenaCatalog:ingredient>
			<tanenaCatalog:confection>
				Confecção
			</tanenaCatalog:confection>
		</tanenaCatalog:course>
	</tanenaCatalog:category>
</tanenaCatalog:catalog>

=== BuiTanDuoc/semestre6/trunk/SI2/Práticas/31401/catalog.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tanenaCatalog:catalog xmlns:tanenaCatalog="http://TantrasEnamour/Catalog"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://TantrasEnamour/Catalog catalog.xsd">
	<category category_name="Nome da Categoria">
		<course course_id="0" course_name="Nome do Prato" course_price="0.0">
			<ingredient>
					<ingredientRecord id="0" nome="NOME" qtd="1" unidade="Kg"/>
					<ingredientRecord id="1" nome="NOME" qtd="1" unidade="Kg"/>
					<ingredientRecord id="2" nome="NOME" qtd="1.3" unidade="Kg"/>
					<ingredientRecord id="3" nome="NOME" qtd="2" unidade="Kg"/>
					<ingredientRecord id="4" nome="NOME" qtd="6" unidade="Kg"/>
					<ingredientRecord id="5" nome="NOME" qtd="10" unidade="Kg"/>
				</ingredient>
			<confection>
				Bla Bla Bla
			</confection>
		</course>
	</category>
</tanenaCatalog:catalog>
